FROM ubuntu:latest

# Update package lists and install bash if the base image doesn't have it by default
RUN apt-get update && apt-get install -y bash jq curl procps coreutils

WORKDIR /app

COPY agent.sh .

# Make the script executable
RUN chmod +x /app/agent.sh

# Run the script as entrypoint
ENTRYPOINT ["/app/agent.sh"]

# Define default arguments for the ENTRYPOINT command. 
# These can be overridden when running the container.
# CMD ["default_arg1", "default_arg2"]